version: 1.0.{build}
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - shawn@wshawn.com
  subject: '[Conway Game of Life] Build Notification'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
